---
abstract: unknown
author:
  - 'Jarkko Hietaniemi <jhi@iki.fi>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Math::Complex: '0'
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graph
no_index:
  directory:
    - t
    - inc
requires:
  Heap: '0.80'
  List::Util: '1.45'
  Safe: '0'
  Scalar::Util: '0'
  Set::Object: '1.40'
  Storable: '2.05'
  perl: '5.006'
resources:
  bugtracker: https://github.com/graphviz-perl/Graph/issues
  repository: git://github.com/graphviz-perl/Graph.git
version: '0.9724'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
